import fs from 'node:fs';
import path from 'node:path';
import {marked} from 'marked';
const languages=['pl','en','es','de','ja','zh'];
const names={pl:'Polski',en:'English',es:'Español',de:'Deutsch',ja:'日本語',zh:'中文'};
const titles={pl:'Forest Hydrology',en:'Forest Hydrology',es:'Forest Hydrology',de:'Forest Hydrology',ja:'Forest Hydrology',zh:'Forest Hydrology'};
function esc(s){return String(s).replace(/[&<>\"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;','\\':'&#92;'}[m]))}
function parseMeta(md){const m=md.match(/^---\n([\s\S]*?)\n---\n/);const meta={};if(!m)return {meta,body:md};for(const line of m[1].split('\n')){const x=line.match(/^([\w-]+):\s*(.*)$/);if(x)meta[x[1]]=x[2].replace(/^['"]|['"]$/g,'')}return {meta,body:md.slice(m[0].length)} }
function shell(lang,content,title){const dir=lang==='pl'?'':'../'.repeat(1);return `<!doctype html><html lang="${lang}"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="description" content="${esc(title)} — Forest Hydrology"><title>${esc(title)} — Forest Hydrology</title><link rel="stylesheet" href="${dir}assets/css/style.css"></head><body><header class="site-header"><div class="wrap nav"><a class="brand" href="${dir}index.html"><span>FOREST</span><strong>HYDROLOGY</strong></a><nav><a href="${dir}articles/index.html">Articles</a><a href="${dir}research/index.html">Research</a><a href="${dir}gis/index.html">GIS & RS</a><a href="${dir}modelling/index.html">Modelling</a><a href="${dir}video/index.html">Videos</a><a href="${dir}about/index.html">About</a></nav><div class="langs">${languages.map(x=>`<a class="lang ${x===lang?'active':''}" href="${x==='pl'?'../'.repeat(0):'../'}">${names[x]}</a>`).join('')}</div></div></header><main class="article">${content}</main><footer class="footer"><div class="wrap"><span>© 2026 Forest Hydrology</span><span>Science · Water · Forests · Data</span></div></footer></body></html>`}
// This generator is intentionally conservative: translated Markdown is published as language-specific HTML.
for(const lang of languages){const files=lang==='pl'?fs.readdirSync('posts/pl').filter(f=>f.endsWith('.md')&&f!=='README.md'):fs.readdirSync('data/translated').filter(f=>f.endsWith(`.${lang}.md`));const outdir=lang==='pl'?'articles':`${lang}/articles`;fs.mkdirSync(outdir,{recursive:true});for(const f of files){const md=fs.readFileSync(lang==='pl'?path.join('posts/pl',f):path.join('data/translated',f),'utf8');const {meta,body}=parseMeta(md);const html=`<p class="eyebrow">${esc(meta.type||'ARTICLE')} · ${esc(meta.date||'')}</p>${marked.parse(body)}`;const slug=(f.replace(/\.md$/,'').replace(/\.[a-z]{2}$/,''));fs.writeFileSync(path.join(outdir,`${slug}.html`),shell(lang,html,meta.title||slug));}}
