baseURL = "https://foresthydrology.com/"
languageCode = "pl-PL"
title = "Forest Hydrology"
theme = ""
paginate = 10

[params]
  author = "Forest Hydrology Team"
  description = "Badania i zasoby dotyczące hydrologii leśnej"
  favicon = "/images/logo.svg"

[taxonomies]
  tag = "tags"
  category = "categories"

[permalinks]
  posts = "/blog/:year/:month/:slug/"
